### list usuarios
GET http://localhost:3000/usuarios
### get usuarios
GET http://localhost:3000/usuarios/1c9572dc-bd07-46e7-89a8-eaca809980c6

### POST usuarios
POST http://localhost:3000/usuarios
Content-Type: application/json 

{
      "name": "admin",
      "email": "ti2@contattos.com",
      "password_hash": "admin123"
}

### PATCH usuarios
PATCH http://localhost:3000/usuarios/1c9572dc-bd07-46e7-89a8-eaca809980c6
Content-Type: application/json 

{
      "email": "teste@gmail.com"
}
### DELETE usuarios
DELETE http://localhost:3000/usuarios/1c9572dc-bd07-46e7-89a8-eaca809980c6